server:
  port: 8081
  servlet:
    context-path: /auth-service

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/tanki_game
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

