server:
  port: 8082
  servlet:
    context-path: /game-service

spring:
  application:
    name: game-service

value: 2

areal:
  stepX : 10
  stepY : 10

object :
  radius : 10

threads-value : 5

auth-service:
  url: http://localhost:8085/auth-service
  user: User_123
  password: 123

