version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: tanki_game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tanki_game
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  mail-service:
    build: ./email-service
    ports:
      - "8082:8082"

  auth-service:
    build: ./auth-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tanki_game
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  game-service:
    build: ./game-service # Путь к вашему проекту game-service
    ports:
      - "8084:8080" # Предполагаем, что ваше приложение слушает на порту 8080
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tanki_game
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # Другие переменные окружения для вашего сервиса, если нужно

volumes:
  postgres_data:
