version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8085:8085"
  game-service:
    build: ./game-service
    ports:
      - "8082:8082"

  user-service:
    build: ./user-service
    ports:
      - "8088:8088"
