server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tanki_game
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres
      mode: always

auth-service:
  url: http://localhost:8081/auth

jwt:
  secret: your_jwt_secret_key


