server:
  port: 8088
  servlet:
    context-path: /user-service

spring:
  application:
    name: user-service


auth-service:
  url: http://localhost:8085/auth-service
  user: User_123
  password: 123

game-service:
  url: http://localhost:8082/game-service/game

basePathForJson: "jsons/command/"